/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface AbiInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "admin"
      | "changeAdmin"
      | "getTouristInfo"
      | "getTouristQRCode"
      | "issueTouristId"
      | "revokeTouristId"
      | "touristQRCodes"
      | "tourists"
      | "verifyTouristHashes"
      | "verifyTouristId"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AdminChanged"
      | "TouristIdIssued"
      | "TouristIdRevoked"
  ): EventFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "changeAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTouristInfo",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTouristQRCode",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "issueTouristId",
    values: [BytesLike, BytesLike, BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeTouristId",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "touristQRCodes",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "tourists", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "verifyTouristHashes",
    values: [BytesLike, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyTouristId",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "changeAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTouristInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTouristQRCode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "issueTouristId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeTouristId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "touristQRCodes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tourists", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifyTouristHashes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyTouristId",
    data: BytesLike
  ): Result;
}

export namespace AdminChangedEvent {
  export type InputTuple = [oldAdmin: AddressLike, newAdmin: AddressLike];
  export type OutputTuple = [oldAdmin: string, newAdmin: string];
  export interface OutputObject {
    oldAdmin: string;
    newAdmin: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TouristIdIssuedEvent {
  export type InputTuple = [
    touristId: BytesLike,
    issuer: AddressLike,
    qrCode: string
  ];
  export type OutputTuple = [touristId: string, issuer: string, qrCode: string];
  export interface OutputObject {
    touristId: string;
    issuer: string;
    qrCode: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TouristIdRevokedEvent {
  export type InputTuple = [touristId: BytesLike, revoker: AddressLike];
  export type OutputTuple = [touristId: string, revoker: string];
  export interface OutputObject {
    touristId: string;
    revoker: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Abi extends BaseContract {
  connect(runner?: ContractRunner | null): Abi;
  waitForDeployment(): Promise<this>;

  interface: AbiInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admin: TypedContractMethod<[], [string], "view">;

  changeAdmin: TypedContractMethod<
    [_newAdmin: AddressLike],
    [void],
    "nonpayable"
  >;

  getTouristInfo: TypedContractMethod<
    [_touristId: BytesLike],
    [
      [string, string, string, string, bigint, bigint, boolean] & {
        touristId: string;
        kycHash: string;
        itineraryHash: string;
        emergencyHash: string;
        startDate: bigint;
        endDate: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  getTouristQRCode: TypedContractMethod<
    [_touristId: BytesLike],
    [string],
    "view"
  >;

  issueTouristId: TypedContractMethod<
    [
      _kycHash: BytesLike,
      _itineraryHash: BytesLike,
      _emergencyHash: BytesLike,
      _startDate: BigNumberish,
      _endDate: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  revokeTouristId: TypedContractMethod<
    [_touristId: BytesLike],
    [void],
    "nonpayable"
  >;

  touristQRCodes: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  tourists: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, string, bigint, bigint, boolean] & {
        touristId: string;
        kycHash: string;
        itineraryHash: string;
        emergencyHash: string;
        startDate: bigint;
        endDate: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  verifyTouristHashes: TypedContractMethod<
    [
      _touristId: BytesLike,
      _kycHash: BytesLike,
      _itineraryHash: BytesLike,
      _emergencyHash: BytesLike
    ],
    [boolean],
    "view"
  >;

  verifyTouristId: TypedContractMethod<
    [_touristId: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "changeAdmin"
  ): TypedContractMethod<[_newAdmin: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getTouristInfo"
  ): TypedContractMethod<
    [_touristId: BytesLike],
    [
      [string, string, string, string, bigint, bigint, boolean] & {
        touristId: string;
        kycHash: string;
        itineraryHash: string;
        emergencyHash: string;
        startDate: bigint;
        endDate: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTouristQRCode"
  ): TypedContractMethod<[_touristId: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "issueTouristId"
  ): TypedContractMethod<
    [
      _kycHash: BytesLike,
      _itineraryHash: BytesLike,
      _emergencyHash: BytesLike,
      _startDate: BigNumberish,
      _endDate: BigNumberish
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeTouristId"
  ): TypedContractMethod<[_touristId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "touristQRCodes"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "tourists"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, string, bigint, bigint, boolean] & {
        touristId: string;
        kycHash: string;
        itineraryHash: string;
        emergencyHash: string;
        startDate: bigint;
        endDate: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "verifyTouristHashes"
  ): TypedContractMethod<
    [
      _touristId: BytesLike,
      _kycHash: BytesLike,
      _itineraryHash: BytesLike,
      _emergencyHash: BytesLike
    ],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "verifyTouristId"
  ): TypedContractMethod<[_touristId: BytesLike], [boolean], "view">;

  getEvent(
    key: "AdminChanged"
  ): TypedContractEvent<
    AdminChangedEvent.InputTuple,
    AdminChangedEvent.OutputTuple,
    AdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "TouristIdIssued"
  ): TypedContractEvent<
    TouristIdIssuedEvent.InputTuple,
    TouristIdIssuedEvent.OutputTuple,
    TouristIdIssuedEvent.OutputObject
  >;
  getEvent(
    key: "TouristIdRevoked"
  ): TypedContractEvent<
    TouristIdRevokedEvent.InputTuple,
    TouristIdRevokedEvent.OutputTuple,
    TouristIdRevokedEvent.OutputObject
  >;

  filters: {
    "AdminChanged(address,address)": TypedContractEvent<
      AdminChangedEvent.InputTuple,
      AdminChangedEvent.OutputTuple,
      AdminChangedEvent.OutputObject
    >;
    AdminChanged: TypedContractEvent<
      AdminChangedEvent.InputTuple,
      AdminChangedEvent.OutputTuple,
      AdminChangedEvent.OutputObject
    >;

    "TouristIdIssued(bytes32,address,string)": TypedContractEvent<
      TouristIdIssuedEvent.InputTuple,
      TouristIdIssuedEvent.OutputTuple,
      TouristIdIssuedEvent.OutputObject
    >;
    TouristIdIssued: TypedContractEvent<
      TouristIdIssuedEvent.InputTuple,
      TouristIdIssuedEvent.OutputTuple,
      TouristIdIssuedEvent.OutputObject
    >;

    "TouristIdRevoked(bytes32,address)": TypedContractEvent<
      TouristIdRevokedEvent.InputTuple,
      TouristIdRevokedEvent.OutputTuple,
      TouristIdRevokedEvent.OutputObject
    >;
    TouristIdRevoked: TypedContractEvent<
      TouristIdRevokedEvent.InputTuple,
      TouristIdRevokedEvent.OutputTuple,
      TouristIdRevokedEvent.OutputObject
    >;
  };
}
